var data = {
    "DynamicNetwork": {
        "MetaNetwork": {
            "documents": {
                "document": {
                    "_id": "dolphins.gml"
                }
            },
            "nodes": {
                "nodeclass": {
                    "node": [{
                        "_id": "0",
                        "_title": "Beak"
                    }, {
                        "_id": "1",
                        "_title": "Beescratch"
                    }, {
                        "_id": "2",
                        "_title": "Bumper"
                    }, {
                        "_id": "3",
                        "_title": "CCL"
                    }, {
                        "_id": "4",
                        "_title": "Cross"
                    }, {
                        "_id": "5",
                        "_title": "DN16"
                    }, {
                        "_id": "6",
                        "_title": "DN21"
                    }, {
                        "_id": "7",
                        "_title": "DN63"
                    }, {
                        "_id": "8",
                        "_title": "Double"
                    }, {
                        "_id": "9",
                        "_title": "Feather"
                    }, {
                        "_id": "10",
                        "_title": "Fish"
                    }, {
                        "_id": "11",
                        "_title": "Five"
                    }, {
                        "_id": "12",
                        "_title": "Fork"
                    }, {
                        "_id": "13",
                        "_title": "Gallatin"
                    }, {
                        "_id": "14",
                        "_title": "Grin"
                    }, {
                        "_id": "15",
                        "_title": "Haecksel"
                    }, {
                        "_id": "16",
                        "_title": "Hook"
                    }, {
                        "_id": "17",
                        "_title": "Jet"
                    }, {
                        "_id": "18",
                        "_title": "Jonah"
                    }, {
                        "_id": "19",
                        "_title": "Knit"
                    }, {
                        "_id": "20",
                        "_title": "Kringel"
                    }, {
                        "_id": "21",
                        "_title": "MN105"
                    }, {
                        "_id": "22",
                        "_title": "MN23"
                    }, {
                        "_id": "23",
                        "_title": "MN60"
                    }, {
                        "_id": "24",
                        "_title": "MN83"
                    }, {
                        "_id": "25",
                        "_title": "Mus"
                    }, {
                        "_id": "26",
                        "_title": "Notch"
                    }, {
                        "_id": "27",
                        "_title": "Number1"
                    }, {
                        "_id": "28",
                        "_title": "Oscar"
                    }, {
                        "_id": "29",
                        "_title": "Patchback"
                    }, {
                        "_id": "30",
                        "_title": "PL"
                    }, {
                        "_id": "31",
                        "_title": "Quasi"
                    }, {
                        "_id": "32",
                        "_title": "Ripplefluke"
                    }, {
                        "_id": "33",
                        "_title": "Scabs"
                    }, {
                        "_id": "34",
                        "_title": "Shmuddel"
                    }, {
                        "_id": "35",
                        "_title": "SMN5"
                    }, {
                        "_id": "36",
                        "_title": "SN100"
                    }, {
                        "_id": "37",
                        "_title": "SN4"
                    }, {
                        "_id": "38",
                        "_title": "SN63"
                    }, {
                        "_id": "39",
                        "_title": "SN89"
                    }, {
                        "_id": "40",
                        "_title": "SN9"
                    }, {
                        "_id": "41",
                        "_title": "SN90"
                    }, {
                        "_id": "42",
                        "_title": "SN96"
                    }, {
                        "_id": "43",
                        "_title": "Stripes"
                    }, {
                        "_id": "44",
                        "_title": "Thumper"
                    }, {
                        "_id": "45",
                        "_title": "Topless"
                    }, {
                        "_id": "46",
                        "_title": "TR120"
                    }, {
                        "_id": "47",
                        "_title": "TR77"
                    }, {
                        "_id": "48",
                        "_title": "TR82"
                    }, {
                        "_id": "49",
                        "_title": "TR88"
                    }, {
                        "_id": "50",
                        "_title": "TR99"
                    }, {
                        "_id": "51",
                        "_title": "Trigger"
                    }, {
                        "_id": "52",
                        "_title": "TSN103"
                    }, {
                        "_id": "53",
                        "_title": "TSN83"
                    }, {
                        "_id": "54",
                        "_title": "Upbang"
                    }, {
                        "_id": "55",
                        "_title": "Vau"
                    }, {
                        "_id": "56",
                        "_title": "Wave"
                    }, {
                        "_id": "57",
                        "_title": "Web"
                    }, {
                        "_id": "58",
                        "_title": "Whitetip"
                    }, {
                        "_id": "59",
                        "_title": "Zap"
                    }, {
                        "_id": "60",
                        "_title": "Zig"
                    }, {
                        "_id": "61",
                        "_title": "Zipfel"
                    }],
                    "_id": "agent",
                    "_type": "agent"
                }
            },
            "networks": {
                "network": {
                    "link": [{
                        "_source": "8",
                        "_target": "3",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "9",
                        "_target": "5",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "9",
                        "_target": "6",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "10",
                        "_target": "0",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "10",
                        "_target": "2",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "13",
                        "_target": "5",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "13",
                        "_target": "6",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "13",
                        "_target": "9",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "14",
                        "_target": "0",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "14",
                        "_target": "3",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "15",
                        "_target": "0",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "16",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "17",
                        "_target": "1",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "17",
                        "_target": "6",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "17",
                        "_target": "9",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "17",
                        "_target": "13",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "18",
                        "_target": "15",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "19",
                        "_target": "1",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "19",
                        "_target": "7",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "20",
                        "_target": "8",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "20",
                        "_target": "16",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "20",
                        "_target": "18",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "21",
                        "_target": "18",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "22",
                        "_target": "17",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "24",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "24",
                        "_target": "15",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "24",
                        "_target": "18",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "25",
                        "_target": "17",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "26",
                        "_target": "1",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "26",
                        "_target": "25",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "27",
                        "_target": "1",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "27",
                        "_target": "7",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "27",
                        "_target": "17",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "27",
                        "_target": "25",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "27",
                        "_target": "26",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "28",
                        "_target": "1",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "28",
                        "_target": "8",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "28",
                        "_target": "20",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "29",
                        "_target": "10",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "29",
                        "_target": "18",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "29",
                        "_target": "21",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "29",
                        "_target": "24",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "30",
                        "_target": "7",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "30",
                        "_target": "19",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "30",
                        "_target": "28",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "31",
                        "_target": "17",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "32",
                        "_target": "9",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "32",
                        "_target": "13",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "33",
                        "_target": "12",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "33",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "33",
                        "_target": "16",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "33",
                        "_target": "21",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "34",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "34",
                        "_target": "33",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "35",
                        "_target": "29",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "36",
                        "_target": "1",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "36",
                        "_target": "20",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "36",
                        "_target": "23",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "37",
                        "_target": "8",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "37",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "37",
                        "_target": "16",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "37",
                        "_target": "21",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "37",
                        "_target": "33",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "37",
                        "_target": "34",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "37",
                        "_target": "36",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "38",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "38",
                        "_target": "16",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "38",
                        "_target": "20",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "38",
                        "_target": "33",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "39",
                        "_target": "36",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "40",
                        "_target": "0",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "40",
                        "_target": "7",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "40",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "40",
                        "_target": "15",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "40",
                        "_target": "33",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "40",
                        "_target": "36",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "40",
                        "_target": "37",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "41",
                        "_target": "1",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "41",
                        "_target": "9",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "41",
                        "_target": "13",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "42",
                        "_target": "0",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "42",
                        "_target": "2",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "42",
                        "_target": "10",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "42",
                        "_target": "30",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "43",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "43",
                        "_target": "29",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "43",
                        "_target": "33",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "43",
                        "_target": "37",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "43",
                        "_target": "38",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "44",
                        "_target": "2",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "44",
                        "_target": "20",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "44",
                        "_target": "34",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "44",
                        "_target": "38",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "45",
                        "_target": "8",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "45",
                        "_target": "15",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "45",
                        "_target": "18",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "45",
                        "_target": "21",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "45",
                        "_target": "23",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "45",
                        "_target": "24",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "45",
                        "_target": "29",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "45",
                        "_target": "37",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "46",
                        "_target": "43",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "47",
                        "_target": "0",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "47",
                        "_target": "10",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "47",
                        "_target": "20",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "47",
                        "_target": "28",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "47",
                        "_target": "30",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "47",
                        "_target": "42",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "49",
                        "_target": "34",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "49",
                        "_target": "46",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "50",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "50",
                        "_target": "16",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "50",
                        "_target": "20",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "50",
                        "_target": "33",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "50",
                        "_target": "42",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "50",
                        "_target": "45",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "51",
                        "_target": "4",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "51",
                        "_target": "11",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "51",
                        "_target": "18",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "51",
                        "_target": "21",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "51",
                        "_target": "23",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "51",
                        "_target": "24",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "51",
                        "_target": "29",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "51",
                        "_target": "45",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "51",
                        "_target": "50",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "52",
                        "_target": "14",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "52",
                        "_target": "29",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "52",
                        "_target": "38",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "52",
                        "_target": "40",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "53",
                        "_target": "43",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "54",
                        "_target": "1",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "54",
                        "_target": "6",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "54",
                        "_target": "7",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "54",
                        "_target": "13",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "54",
                        "_target": "19",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "54",
                        "_target": "41",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "55",
                        "_target": "15",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "55",
                        "_target": "51",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "56",
                        "_target": "5",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "56",
                        "_target": "6",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "57",
                        "_target": "5",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "57",
                        "_target": "6",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "57",
                        "_target": "9",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "57",
                        "_target": "13",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "57",
                        "_target": "17",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "57",
                        "_target": "39",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "57",
                        "_target": "41",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "57",
                        "_target": "48",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "57",
                        "_target": "54",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "58",
                        "_target": "38",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "59",
                        "_target": "3",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "59",
                        "_target": "8",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "59",
                        "_target": "15",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "59",
                        "_target": "36",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "59",
                        "_target": "45",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "60",
                        "_target": "32",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "61",
                        "_target": "2",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "61",
                        "_target": "37",
                        "_type": "integer",
                        "_value": "1"
                    }, {
                        "_source": "61",
                        "_target": "53",
                        "_type": "integer",
                        "_value": "1"
                    }],
                    "_id": "agent x agent",
                    "_isDirected": "false",
                    "_source": "agent",
                    "_target": "agent"
                }
            }
        }
    }
};